apiVersion: v1
kind: Service
metadata:
  name: ipcc-microfrontend-service
  labels:
    app: ipcc-microfrontend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: ipcc-microfrontend
